.pragma library

// Apps whose own mark replaces their Material Symbols category glyph in the
// bar's window icons (Workspaces, SpecialWorkspaces). Caelestia draws every
// window as its category glyph, so all terminals look alike; a terminal you
// live in is easier to spot as itself.
//
// Same shape as a Logos.js path option, so LogoIcon draws it: an outline in
// a 1000 x 1000 box (y down), role "fg" tinted. Hand-drawn rather than
// generated by scripts/gen-logos.py, since no installed font carries these
// marks. Holes are wound opposite to the body (SVG's nonzero rule).

var options = [
  // Ghostty's ghost with its ">-" face cut out.
  { id: "ghostty", kind: "path", aspect: 0.780, paths: [["fg",
    "M110 400C110 170 280 0 500 0C720 0 890 170 890 400L890 900C890 985 800 1020 740 960C700 920 650 920 610 960C560 1010 440 1010 390 960C350 920 300 920 260 960C200 1020 110 985 110 900Z"
    + "M298 338L242 422L360 500L242 578L298 662L540 500Z"
    + "M590 455L590 545L770 545L770 455Z"]] }
]

var classes = {
  "com.mitchellh.ghostty": "ghostty",
  "ghostty": "ghostty"
}

function forClass(cls) {
  var id = classes[String(cls || "").toLowerCase()]
  if (!id) return null
  for (var i = 0; i < options.length; i++) if (options[i].id === id) return options[i]
  return null
}
